### ISSUE TITLE
t/pty_get_winsize.t fails on AIX

### ISSUE THREAD

**Issue by mbuchanan** [cpan-authors/IO-Tty#32]
"make test" fails on AIX in t/pty_get_winsize.t:

Cannot TIOCGWINSZ - Invalid argument at t/pty_get_winsize.t line 25.

The "invalid argument" appears to be the filehandle passed to ioctl.  I wrote a small test program to verify that the TIOCGWINSZ ioctl works when called on STDIN, and then repeated the get_winsize() test:

```
use strict;
use warnings;
use IO::Pty ();
use Data::Dumper;

print "Current tty = ";
system "tty";
ioctl STDIN, IO::Tty::Constant::TIOCGWINSZ(), my $winsize = q<> or die $!;
print Dumper [ IO::Tty::unpack_winsize($winsize) ];

my $pty = IO::Pty->new();
print "New pty = ", $pty->ttyname, "\n";
print Dumper [ $pty->get_winsize() ];
```

Here is its output:

```
Current tty = /dev/pts/0
$VAR1 = [
          55,
          195,
          1192,
          722
        ];
New pty = /dev/pts/2
Cannot TIOCGWINSZ - Invalid argument at /home/builder/iotty line 15.

```

I've attached the output of "perl Makefile.PL" and "make test".  This is on Perl 5.34.0 and AIX 7.1.5.4.

[build.log](https://github.com/toddr/IO-Tty/files/6843366/build.log)

**Comment by XSven** [comment]
I have detected the same issue on AIX 7.2.5.2 with Perl: 5.14.2 and IO-Tty-1.16.

**Comment by EGuesnet** [comment]
I confirm the bug (AIX 7.1, perl 5.34.0).
Workaround patch:

```
--- t/pty_get_winsize.t.orig  2021-01-22 09:02:35.000000000 +0000
+++ t/pty_get_winsize.t       2021-11-16 10:45:42.414831201 +0000
@@ -5,8 +5,8 @@

 use Test::More;

-if ( $^O =~ m!^(solaris|nto)$! ) {
-    plan skip_all => 'Problems on Solaris and QNX with this test';
+if ( $^O =~ m!^(solaris|nto|aix)$! ) {
+    plan skip_all => 'Problems on Solaris, QNX and AIX with this test';
 }
 else {
     plan tests => 1;
```
